version: 0.2

env:
  variables:
    S3_BUCKET: theartofgin-codebuild-artifacts
    S3_SAM_PREFIX: sam-artifacts


phases:
  build:
    commands:
      - pip install --upgrade awscli
      - |
        aws cloudformation package --s3-bucket $S3_BUCKET --s3-prefix $S3_SAM_PREFIX \
            --template template.yml \
            --output-template template-export.yml


artifacts:
 type: zip
 files:
   - template-export.yml
