AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    Description: The project name to associate this stack to
    Default: theartofgin

Resources:
  LambdaTrustRole:
    Type: AWS::IAM::Role
    Properties:
        Path: /
        RoleName: !Sub ${ProjectName}-LambdaDynamoDBAccess
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Action: 'sts:AssumeRole'
              Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
        Policies:
        - PolicyName: !Sub ${ProjectName}-LambdaDynamoDBPolicyName
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                - dynamodb:GetItem
                - dynamodb:DescribeTable
                - dynamodb:Scan
                - dynamodb:Query
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                Effect: Allow
                Resource: !GetAtt GinReviews.Arn
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      Role: !GetAtt LambdaTrustRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
  PostGinReview:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.post_gin_review
      Runtime: python3.6
      Role: !GetAtt LambdaTrustRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /review
            Method: post
  GinReviews:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: reviewId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
