Description: v0.1 | theartofgin | Leo Roos | Initial Setup Dependencies
Parameters:
    ProjectName:
      Description: A project name that will be prefixed to resource names
      Type: String
      Default: theartofgin

Resources:
    CodeDeployServiceRole: 
        Type: AWS::IAM::Role
        Properties:
            Path: /
            RoleName: !Sub ${ProjectName}-CodeDeployServiceRole
            AssumeRolePolicyDocument:
              Version: 2012-10-17
              Statement:
              - Action: 'sts:AssumeRole'
                Effect: Allow
                Principal:
                  Service: codedeploy.amazonaws.com
            ManagedPolicyArns:
              - 'arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda'
    CodePipelineServiceRole: 
        Type: AWS::IAM::Role
        Properties:
            Path: /
            RoleName: !Sub ${ProjectName}-CodePipelineServiceRole
            AssumeRolePolicyDocument:
              Version: 2012-10-17
              Statement:
              - Action: 'sts:AssumeRole'
                Effect: Allow
                Principal:
                  Service: codepipeline.amazonaws.com
            Policies:
            - PolicyName: !Sub ${ProjectName}-CodePipelineServicePolicy
              PolicyDocument:
                Version: 2012-10-17
                Statement:
                  - Action:
                    - s3:GetObject
                    - s3:GetObjectVersion
                    - s3:GetBucketVersioning
                    Resource: "*"
                    Effect: Allow
                  - Action:
                    - s3:PutObject
                    Resource:
                    - arn:aws:s3:::codepipeline*
                    - arn:aws:s3:::codebuild*
                    Effect: Allow
                  - Action:
                    - codedeploy:CreateDeployment
                    - codedeploy:GetApplicationRevision
                    - codedeploy:GetDeployment
                    - codedeploy:GetDeploymentConfig
                    - codedeploy:RegisterApplicationRevision
                    Resource: "*"
                    Effect: Allow
                  - Action:
                    - cloudformation:GetTemplate
                    - cloudformation:DescribeStackResource
                    - cloudformation:DescribeStackResources
                    - cloudformation:DescribeStackEvents
                    - cloudformation:DescribeStacks
                    - cloudformation:UpdateStack
                    - sns:ListSubscriptionsByTopic
                    Resource: "*"
                    Effect: Allow
                  - Action:
                    - lambda:invokefunction
                    - lambda:listfunctions
                    Resource: "*"
                    Effect: Allow
                  - Action:
                    - cloudformation:CreateStack
                    - cloudformation:DeleteStack
                    - cloudformation:DescribeStacks
                    - cloudformation:UpdateStack
                    - cloudformation:CreateChangeSet
                    - cloudformation:DeleteChangeSet
                    - cloudformation:DescribeChangeSet
                    - cloudformation:ExecuteChangeSet
                    - cloudformation:SetStackPolicy
                    - cloudformation:ValidateTemplate
                    - iam:PassRole
                    Resource: "*"
                    Effect: Allow
                  - Action:
                    - codebuild:BatchGetBuilds
                    - codebuild:StartBuild
                    Effect: Allow
                    Resource: "*"
    CodePipelineCloudformationServiceRole: 
        Type: AWS::IAM::Role
        Properties:
            Path: /
            RoleName: !Sub ${ProjectName}-CodePipelineCloudformationServiceRole
            AssumeRolePolicyDocument:
              Version: 2012-10-17
              Statement:
              - Action: 'sts:AssumeRole'
                Effect: Allow
                Principal:
                  Service: cloudformation.amazonaws.com
            Policies:
            - PolicyName: !Sub ${ProjectName}-CodePipelineCloudformationServicePolicy
              PolicyDocument:
                Version: 2012-10-17
                Statement:
                  - Action:
                    - s3:PutObject
                    - s3:GetObject
                    - s3:GetObjectVersion
                    Resource: "*"
                    Effect: Allow
                  - Action:
                    - lambda:CreateFunction
                    - lambda:DeleteFunction
                    - lambda:AddPermission
                    - lambda:UpdateFunction
                    - lambda:UpdateFunctionCode
                    - lambda:GetFunction
                    - lambda:GetFunctionConfiguration
                    - lambda:UpdateFunctionConfiguration
                    - lambda:RemovePermission
                    - lambda:listTags
                    - lambda:TagResource
                    - lambda:UntagResource
                    - apigateway:*
                    - dynamodb:CreateTable
                    - dynamodb:DeleteTable
                    - dynamodb:DescribeTable
                    - sns:CreateTopic
                    - sns:DeleteTopic
                    - sns:ListTopics
                    - sns:GetTopicAttributes
                    - sns:SetTopicAttributes
                    - s3:CreateBucket
                    - s3:DeleteBucket
                    Resource: "*"
                    Effect: Allow
                  - Action:
                    - iam:PassRole
                    Resource: "*"
                    Effect: Allow
                  - Action:
                    - cloudformation:CreateChangeSet
                    Resource: "*"
                    Effect: Allow



