Description: v0.1 | theartofgin | Leo Roos | Initial Setup Dependencies
Parameters:
  ProjectName:
    Description: A project name that will be prefixed to resource names
    Type: String
    Default: theartofgin

Resources:
  # CodeDeployServiceRole:
  #     Type: AWS::IAM::Role
  #     Properties:
  #         Path: /
  #         RoleName: !Sub ${ProjectName}-CodeDeployServiceRole
  #         AssumeRolePolicyDocument:
  #           Version: 2012-10-17
  #           Statement:
  #           - Action: 'sts:AssumeRole'
  #             Effect: Allow
  #             Principal:
  #               Service: codedeploy.amazonaws.com
  #         ManagedPolicyArns:
  #           - 'arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda'
  CodeBuildServiceRole:
      Type: AWS::IAM::Role
      Properties:
          Path: /
          RoleName: !Sub ${ProjectName}-CodeBuildServiceRole
          AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
            - Action: 'sts:AssumeRole'
              Effect: Allow
              Principal:
                Service: codebuild.amazonaws.com
          Policies:
          - PolicyName: !Sub ${ProjectName}-CodeBuildServicePolicy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
              - Effect: Allow
                Resource:
                - arn:aws:logs:eu-central-1:872695986225:log-group:/aws/codebuild/theartofgin*
                Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              - Effect: Allow
                Resource:
                - arn:aws:s3:::theartofgin-codebuild-artifacts/*
                - !Sub "${WebsiteBucket.Arn}/*"
                - arn:aws:s3:::codepipeline-eu-central-1-*
                Action:
                - s3:PutObject
              - Effect: Allow
                Action:
                - s3:GetObject
                - s3:GetObjectVersion
                Resource: '*'
              - Effect: Allow
                Resource:
                - arn:aws:ssm:eu-central-1:872695986225:parameter/theartofgin/*
                Action:
                - ssm:GetParameters
              - Effect: Allow
                Resource:
                - arn:aws:cloudformation:eu-central-1:872695986225:stack/theartofgin-*
                Action:
                - cloudformation:UpdateStack
  CodePipelineServiceRole:
      Type: AWS::IAM::Role
      Properties:
          Path: /
          RoleName: !Sub ${ProjectName}-CodePipelineServiceRole
          AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
            - Action: 'sts:AssumeRole'
              Effect: Allow
              Principal:
                Service: codepipeline.amazonaws.com
          Policies:
          - PolicyName: !Sub ${ProjectName}-CodePipelineServicePolicy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  Resource: "*"
                  Effect: Allow
                - Action:
                  - s3:PutObject
                  Resource:
                  - arn:aws:s3:::codepipeline*
                  - arn:aws:s3:::codebuild*
                  Effect: Allow
                - Action:
                  - codedeploy:CreateDeployment
                  - codedeploy:GetApplicationRevision
                  - codedeploy:GetDeployment
                  - codedeploy:GetDeploymentConfig
                  - codedeploy:RegisterApplicationRevision
                  Resource: "*"
                  Effect: Allow
                - Action:
                  - cloudformation:GetTemplate
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - sns:ListSubscriptionsByTopic
                  Resource: "*"
                  Effect: Allow
                - Action:
                  - lambda:invokefunction
                  - lambda:listfunctions
                  Resource: "*"
                  Effect: Allow
                - Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                  - iam:PassRole
                  Resource: "*"
                  Effect: Allow
                - Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                  Effect: Allow
                  Resource: "*"
  CodePipelineCloudformationServiceRole:
      Type: AWS::IAM::Role
      Properties:
          Path: /
          RoleName: !Sub ${ProjectName}-CodePipelineCloudformationServiceRole
          AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
            - Action: 'sts:AssumeRole'
              Effect: Allow
              Principal:
                Service: cloudformation.amazonaws.com
          Policies:
          - PolicyName: !Sub ${ProjectName}-CodePipelineCloudformationServicePolicy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Action: '*'
                  Resource: "*"
                  Effect: Allow
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: theartofgin.lroos.com
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  WebsiteBucketSSMParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /theartofgin/websitebucket
      Type: String
      Value: !Ref WebsiteBucket
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: WebsiteBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${WebsiteBucket}/*'
      Bucket: !Ref WebsiteBucket
  CodeBuildBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: theartofgin-codebuild
  CodeBuildBucketSSMParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /theartofgin/codbuildbucket
      Type: String
      Value: !Ref WebsiteBucket

